# Generated by Django 2.1 on 2018-08-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0002_superhero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superhero',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
