# Generated by Django 2.1 on 2018-08-28 10:46

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0003_auto_20180828_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
    ]
