# Generated by Django 2.1 on 2018-08-28 10:41

from django.db import migrations
from django.utils.text import slugify


def populate_slug(apps, schema_editor):
    Superhero = apps.get_model('supers', 'Superhero')
    for superhero in Superhero.objects.all():
        superhero.slug = slugify(superhero.name)
        superhero.save()

    # Making slugs unique
    all_slugs = [x.slug for x in Superhero.objects.all()]

    for superhero in Superhero.objects.all():
        slug_repeats = all_slugs.count(superhero.slug)
        if slug_repeats > 1:
            superhero.slug = superhero.slug + '-{}'.format(slug_repeats)
            superhero.save()
            all_slugs = [x.slug for x in Superhero.objects.all()]


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0004_superhero_slug'),
    ]

    operations = [
        migrations.RunPython(
            populate_slug, reverse_code=migrations.RunPython.noop
        )
    ]
